name: periodic-graph
channels:
  - defaults
dependencies:
  - pip:
      - absl-py==2.1.0
      - astunparse==1.6.3
      - cachetools==5.3.2
      - calmap==0.0.11
      - cython==0.29.37
      - dgl==1.1.2.post1
      - dtaidistance==2.3.11
      - et-xmlfile==1.1.0
      - fastdtw==0.3.4
      - filelock==3.13.1
      - flatbuffers==23.5.26
      - frozendict==2.4.0
      - fsspec==2023.12.2
      - gast==0.4.0
      - google-auth==2.27.0
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - grpcio==1.60.0
      - h5py==3.10.0
      - hdbscan==0.8.33
      - idx2numpy==1.2.3
      - joblib==1.3.2
      - keras==2.13.1
      - lazy-object-proxy==1.10.0
      - libclang==16.0.6
      - llvmlite==0.41.1
      - markdown==3.5.2
      - mass-ts==0.1.3
      - mpmath==1.3.0
      - natsort==8.4.0
      - networkx==3.1
      - numba==0.58.1
      - numpy==1.22.4
      - oauthlib==3.2.2
      - openpyxl==3.1.2
      - opt-einsum==3.3.0
      - pandas==2.0.3
      - patsy==0.5.6
      - pot==0.9.3
      - protobuf==3.20.0
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pywavelets==1.4.1
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - scikit-learn==1.3.2
      - scipy==1.7.1
      - seaborn==0.13.1
      - semver==3.0.2
      - spot==0.1a0
      - statsmodels==0.14.1
      - sympy==1.12
      - tabulate==0.9.0
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.13.1
      - tensorflow-estimator==2.13.0
      - tensorflow-io-gcs-filesystem==0.34.0
      - termcolor==2.4.0
      - tfsnippet==0.2.0a1
      - threadpoolctl==3.2.0
      - timepy==0.1a0
      - torch==2.1.2
      - tqdm==4.66.1
      - tslearn==0.6.3
      - typing-extensions==4.5.0
      - tzdata==2023.4
      - werkzeug==3.0.1
      - wrapt==1.16.0
      - xlrd==2.0.1
      - zhusuan==0.4.0